{{- if eq .Values.global.componentsEnable.kubecube "true" }}
apiVersion: hotplug.kubecube.io/v1
kind: Hotplug
metadata:
  name: pivot-cluster
spec:
  component:
    - name: logseer
      status: "{{ .Values.global.hotPlugEnable.pivot.logseer }}"
    - name: logseer-new
      status: "{{ .Values.global.hotPlugEnable.pivot.logseerNew }}"
    - name: logagent-new
      status: "{{ .Values.global.hotPlugEnable.pivot.logagentNew }}"
    - env: |
        grafana:
          enabled: true
        kubeEtcd:
          enabled: false
        prometheus:
          prometheusSpec:
            externalLabels:
              cluster: "{{.cluster}}"
            remoteWrite:
            - url: http://kubecube-thanos-receive:19291/api/v1/receive
      name: kubecube-monitoring
      status: "{{ .Values.global.hotPlugEnable.pivot.monitoring }}"
    - env: |
        receive:
          tsdbRetention: 7d
          replicaCount: 1
          replicationFactor: 1
      name: kubecube-thanos
      status: "{{ .Values.global.hotPlugEnable.pivot.thanos }}"
{{- end }}